# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8911723ae7c6f83e117df5a073401b7a63fe3fa9b5720438c0742d43ec31fde7e8c6348fd1e7e832fe304f6127e77a1bdb12169c60e2dc49cd142c5c7065b6f

test:
  secret_key_base: 3709c5cca6c48ef5048d7038dbe6e430663996aec8eb02b6bbbf3e949cfc2f82de1ea7fc81b989f5eb25f7c3052e3ae6a75bac14a0123d6442c5f4090dc0c505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
